project_id = "mdkcdjltvfpthqudhhmx"

[functions.get-assistants]
verify_jwt = false

[functions.get-embed-mappings]
verify_jwt = false

[functions.save-assistant]
verify_jwt = false

[functions.vapi-list-files]
verify_jwt = false

[functions.vapi-function-calls]
verify_jwt = false

[functions.voice-assistant-embed-js]
verify_jwt = false

[functions.vapi-analytics]
verify_jwt = false

[functions.scrape-website]
verify_jwt = false

[functions.process-knowledge-base]
verify_jwt = false

[functions.check-scrape-status]
verify_jwt = false